version: '2.30.1'

services:

  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./db/:/var/lib/postgresql/data

  src:
    build: src
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./src:/app
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver ${APP_HOST}:${APP_PORT}"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
    env_file:
      - ./.env

  image_processing_app:
    build: image_processing_service
    ports:
      - "${IMAGE_PROCESSING_PORT}:8000"
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - ./image_processing_service:/app
    command:
      - python
      - receive.py
